# Generated by Django 5.2.5 on 2025-09-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.CharField(max_length=100, verbose_name='Picture')),
                ('price', models.FloatField(max_length=100, verbose_name='Price')),
                ('discount', models.IntegerField(verbose_name='Discount')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
