# Generated by Django 5.2.6 on 2025-09-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default=0, null=0, upload_to='product_images/', verbose_name='Image1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=0, null=0, upload_to='product_images/', verbose_name='Image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=0, null=0, upload_to='product_images/', verbose_name='Image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default=0, null=0, upload_to='product_images/', verbose_name='Image4'),
        ),
    ]
