# Generated by Django 5.2.6 on 2025-09-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
