# Generated by Django 5.2.4 on 2025-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bidding_open',
            field=models.BooleanField(default=True),
        ),
    ]
