# Generated by Django 5.2.5 on 2025-10-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
