# Generated by Django 5.2.5 on 2025-08-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_laptop_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='cars/')),
                ('model', models.TextField()),
                ('engine', models.TextField()),
                ('enginepower', models.TextField()),
                ('price', models.TextField()),
                ('madein', models.TextField()),
                ('topspeed', models.TextField()),
            ],
        ),
    ]
