# Generated by Django 5.2.5 on 2025-08-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='enginepower',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='madein',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='topspeed',
            field=models.CharField(max_length=100),
        ),
    ]
